#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 08 09:47:01 +03 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim traffic_light_tb_behav -key {Behavioral:sim_1:Functional:traffic_light_tb} -tclbatch traffic_light_tb.tcl -log simulate.log"
xsim traffic_light_tb_behav -key {Behavioral:sim_1:Functional:traffic_light_tb} -tclbatch traffic_light_tb.tcl -log simulate.log

